In [7]:
from tensorflow.keras.preprocessing.text import one_hot

In [1]:
### Sentences
sent= [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [2]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## define the vocabulary size
voc_size=10000

In [8]:
## one hot representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3064, 1940, 7099, 3526],
 [3064, 1940, 7099, 7775],
 [3064, 1744, 7099, 6306],
 [7548, 8009, 8589, 7443, 645],
 [7548, 8009, 8589, 7443, 3157],
 [6047, 3064, 5912, 7099, 5261],
 [1955, 1883, 1879, 7443]]

In [9]:
## word enbedding Representaion
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [10]:
import numpy as np 


In [ ]:
sent_lenght = 8
embedded_docs=pad_sequences(one_hot_repr,padding='post',maxlen=sent_lenght) ## in padding we can use pre for before words and post for after words
print (embedded_docs)

[[3064 1940 7099 3526    0    0    0    0]
 [3064 1940 7099 7775    0    0    0    0]
 [3064 1744 7099 6306    0    0    0    0]
 [7548 8009 8589 7443  645    0    0    0]
 [7548 8009 8589 7443 3157    0    0    0]
 [6047 3064 5912 7099 5261    0    0    0]
 [1955 1883 1879 7443    0    0    0    0]]


In [14]:
## feature representation
dim=10

In [15]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_lenght))
model.compile('adam','mse')

c:\Users\amrit\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [16]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [17]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 194ms/step


array([[[-1.86024979e-03,  4.86705564e-02, -3.58479843e-02,
         -8.16708803e-03, -2.04252489e-02,  3.80618684e-02,
         -3.78486030e-02,  2.54683979e-02, -1.23850331e-02,
         -3.57219204e-02],
        [ 3.63934673e-02,  2.72521265e-02,  1.76541097e-02,
          4.82250787e-02, -8.08074325e-03,  3.11846770e-02,
         -1.97377093e-02, -2.53060814e-02, -1.24325976e-02,
          1.39456652e-02],
        [-2.52015349e-02,  3.87383141e-02, -2.57265568e-03,
          7.12814182e-03,  2.06375383e-02, -1.25175342e-02,
          4.01595943e-02,  5.60544431e-04, -3.36062312e-02,
          2.73678191e-02],
        [-1.83429942e-02, -3.15249451e-02,  5.73275238e-03,
          3.07544358e-02,  4.25981395e-02, -3.16904075e-02,
          2.47434489e-02,  4.38403152e-02, -8.81686062e-03,
         -2.14216858e-03],
        [-2.88599860e-02,  6.02024794e-03,  4.88591194e-03,
         -4.30953279e-02, -3.82104293e-02, -4.83928323e-02,
         -4.52879928e-02,  3.36271040e-02, -1.002307

In [19]:
model.predict(embedded_docs[[0]])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step


array([[[-0.00186025,  0.04867056, -0.03584798, -0.00816709,
         -0.02042525,  0.03806187, -0.0378486 ,  0.0254684 ,
         -0.01238503, -0.03572192],
        [ 0.03639347,  0.02725213,  0.01765411,  0.04822508,
         -0.00808074,  0.03118468, -0.01973771, -0.02530608,
         -0.0124326 ,  0.01394567],
        [-0.02520153,  0.03873831, -0.00257266,  0.00712814,
          0.02063754, -0.01251753,  0.04015959,  0.00056054,
         -0.03360623,  0.02736782],
        [-0.01834299, -0.03152495,  0.00573275,  0.03075444,
          0.04259814, -0.03169041,  0.02474345,  0.04384032,
         -0.00881686, -0.00214217],
        [-0.02885999,  0.00602025,  0.00488591, -0.04309533,
         -0.03821043, -0.04839283, -0.04528799,  0.0336271 ,
         -0.01002308,  0.01404799],
        [-0.02885999,  0.00602025,  0.00488591, -0.04309533,
         -0.03821043, -0.04839283, -0.04528799,  0.0336271 ,
         -0.01002308,  0.01404799],
        [-0.02885999,  0.00602025,  0.00488591, -0.0